### ISSUE TITLE
Fig 2 y-axis range (IGP strength)

### ISSUE THREAD

**Issue by marknovak** [ingemanKE/IGP-adaptive-defense#3]
Why, in Fig. 2, does the y-axis (IGP strength) range from 1 to 4 rather than 0 to 4? 
The corresponding figure in Nakazawa et al. starts at 0.

**Comment by ingemanKE** [comment]
Open to your thoughts on cherry-picking figure range and parameter values to illustrate takeaways vs staying consistent for clarity and transparency

**Comment by marknovak** [comment]
Clarity (and consistency, as needed) seems the most important, assuming that effects aren't super sensitive to changes.  If they are, then that will need to be addressed explicitly, with parameters justified accordingly.

**Comment by ingemanKE** [comment]
I support that

**Comment by marknovak** [comment]
This is resolved by use of RegionPlot which shows why things broke down in old analyses:  There's a whole lot going on in the `aPN<1` region, including alternative stable states.
